config/routes.rb
Rails.application.routes.draw do
  resources :posts
  root 'posts#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
  	@posts = Post.all.order('created_at DESC')
  	# @posts.delete_all
  	@post = Post.new
  end


  def new
  	@post = Post.new
  end

  def show 
  	@post = set_post(params[:id])
  end

  def edit
  	@post = set_post(params[:id])
  end

  def create
    @post = Post.new(post_params)
    @post.save
	   respond_to do |format|
      		format.html {redirect_to root_path}
      		format.js
    end
  end

  def update
  	@post = set_post(params[:id])

  	@post = set_post(params[:id])
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_path }
        format.js
      else
        format.html { render :edit }
        format.js
      end
    end
  end

  def destroy
  	@post = set_post(params[:id])
  	@post.destroy
  	respond_to do |format|
  	 format.html {redirect_to root_path}
  	 format.js
  	end
  end

  private

	def set_post(post_id)
 	  Post.find(post_id)
	end


    def post_params
  	  params.require(:post).permit(:text)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wall</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">
  </head>

  <body>
    <div id="background-wall"></div>
	  <div class="container">
	    <%= yield %>
	   </div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post, remote: true do |f| %>
	<a id="close" href="javascript:void(0)" > &times</a>
		<%= f.text_area :text, rows: '3' , cols: '70', placeholder: "О чем вы думаете?"  , class: "textarea" %>
	<%= f.submit class: "button"  %> 
<% end %>

app/views/posts/_post.html.erb
<div class="wall-post" id="post_<%= post.id %>"><%= post.text %>
	<%= link_to 'remove', post_path(post.id), method: :delete, data: { confirm: 'Are you sure?' }, id: "remove", remote: true %>
		<button style="top: 50px; left: 70px; position: absolute;" id="edit_<%= post.id %>">
			Edit
		</button>
</div>

app/views/posts/create.js.erb
$(".textarea").val("");
$(".main").prepend("<%= j render(@post) %>");
$("#post_<%= @post.id  %>").hide().fadeIn(1000);

app/views/posts/destroy.js.erb
$("#post_<%= @post.id %>").fadeOut(500, function() {
	$(this).remove();
});

app/views/posts/index.html.erb
<%#= link_to "New Post", new_post_url, id: "new_post", remote: true %>

<div class="form" style="position: relative;">
	<div class="img-block">
		<a href="javascript:void(0)">
			<div class="image" style="background-image: url('/color-pick.png');"></div>
		</a>
		<a href="javascript:void(0)">
			<div class="image" style="background-image: url('/img-1.png');"></div>
		</a>
		<a href="javascript:void(0)">
			<div class="image" style="background-image: url('/img-2.png');"></div>
		</a>
		<a href="javascript:void(0)">
			<div class="image" style="background-image: url('/img-3.png');"></div>
		</a>
		<a href="javascript:void(0)">
			<div class="image" style="background-image: url('/img-4.png');"></div>
		</a>
		<a href="javascript:void(0)">
			<div class="image" style="background-image: url('/img-5.png');"></div>
		</a>
		<a href="javascript:void(0)">
			<div class="image" style="background-image: url('/img-6.png');"></div>
		</a>
		<a href="javascript:void(0)">
			<div class="image" style="background-image: url('/img-7.png');"></div>
		</a>
		<a href="javascript:void(0)">
			<div class="image" style="background-image: url('/img-8.png');"></div>
		</a>
		<a href="javascript:void(0)">
			<div class="image" style="background-image: url('/img-9.png');"></div>
		</a>
	</div>
</div>

<%= render 'form' %>

<div id="place_form"></div>

<div class="main">
	<%= render @posts %>
</div>

app/views/posts/new.html.erb
<div class="post-textarea">
	<%= render 'form' %>
</div>

app/views/posts/new.js.erb
// $('#new_post').hide().after('<%= j render("form") %>');


// $("#close").on("click", function() {
// 	$('form').hide();
// 	$("#new_post").show();
// });